version: "3.9"
services:
  app:
    build:
      context: ./config/php/${SET_PHP_VERSION}
      args:
        SET_XEDEBUG_VERSION: ${SET_XEDEBUG_VERSION}
        SET_HOST_UID: ${SET_HOST_UID}
        SET_HOST_GID: ${SET_HOST_GID}
      dockerfile: Dockerfile

    container_name: ph
    user: ${SET_HOST_UID}:${SET_HOST_GID}
    #user: root
    volumes:
      - ./src:/var/www/htdocs

  server:
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    ports:
      - 8000:80
    container_name: ng
    volumes:
      - ./src:/var/www/htdocs

  db:
    build:
      context: ./config/mariadb
      dockerfile: Dockerfile

    restart: on-failure
    container_name: db
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: example_database
      MARIADB_USER: example_user
      MARIADB_PASSWORD: example_pass
    volumes:
      - ./config/mariadb/storage:/var/lib/mysql
    ports:
      - 8001:3306


  phpmyadmin:
    image: phpmyadmin
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8002:80

  mailhog:
    build:
      context: ./config/mailhog
      dockerfile: Dockerfile
    restart: on-failure
    container_name: mailh
    ports:
      - 8003:8025
