version: "3.9"
services:
  app:
    # php can be switcable using context path
    build:
      context: ./dockerfiles/php/8.1
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/public

  server:
    build:
      context: ./dockerfiles/nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./dockerfiles/nginx/conf:/usr/local/openresty/nginx
