version: "3.9"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
  app:
    build:
      context: ./dockerfiles/php/8.1
      dockerfile: Dockerfile
    container_name: ph
    user: root
    volumes:
      - ./src:/var/www/htdocs

  server:
    build:
      context: ./dockerfiles/nginx
      dockerfile: Dockerfile
    ports:
      - 8000:80
    container_name: ng
    volumes:
      - ./src:/var/www/htdocs

  db:
    build:
      context: ./dockerfiles/mariadb
      dockerfile: Dockerfile

    restart: on-failure
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: example_database
      MARIADB_USER: example_user
      MARIADB_PASSWORD: example_pass
    volumes:
      - ./dockerfiles/mariadb/storage:/var/lib/mysql
    ports:
      - 8001:3306


  phpmyadmin:
    image: phpmyadmin
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8002:80

  mailhog:
    build:
      context: ./dockerfiles/mailhog
      dockerfile: Dockerfile
    restart: on-failure
    container_name: mailh
    ports:
      - 8003:8025
