version: "3.9"
services:
  php:
    build:
      context: ./config/php/${SET_PHP_VERSION}
      dockerfile: Dockerfile
      args:
        SET_XDEBUG_VERSION: ${SET_XDEBUG_VERSION}
        SET_HOST_UID: ${SET_HOST_UID}
        SET_HOST_GID: ${SET_HOST_GID}
    container_name: ${SET_SITE_NAME}_php
    volumes:
      - type: bind
        source: ${SET_SITE_SRC_DIR}
        target: /var/www/htdocs

  server:
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    ports:
      - target: 80
        published: ${SET_PORT_SERVER}
        protocol: tcp
        mode: host
      - target: 443
        published: ${SET_PORT_SERVER_SSL}
        protocol: tcp
        mode: host
    container_name: ${SET_SITE_NAME}_nginx
    volumes:
      - type: bind
        source: ${SET_SITE_SRC_DIR}
        target: /var/www/htdocs
      - type: bind
        source: ./config/nginx/certs
        target: /usr/local/openresty/nginx/certs

  db:
    build:
      context: ./config/mariadb
      dockerfile: Dockerfile
      args:
        SET_HOST_UID: ${SET_HOST_UID}

    restart: on-failure
    container_name: ${SET_SITE_NAME}_db
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: example_database
      MARIADB_USER: example_user
      MARIADB_PASSWORD: example_pass

    #user: ${SET_HOST_UID}:${SET_HOST_GID}
    volumes:
      - type: bind
        source: ${SET_SITE_MARIADB_DIR}
        target: /var/lib/mysql
    expose:
      - 3306

  phpmyadmin:
    build:
      context: ./config/phpmyadmin
      dockerfile: Dockerfile
    restart: on-failure
    container_name: ${SET_SITE_NAME}_phpmyadmin
    depends_on:
      - db
    environment:
      PMA_USER: example_user
      PMA_PASSWORD: example_pass
    ports:
      - target: 80
        published: ${SET_PORT_PHPMYADMIN}
        protocol: tcp
        mode: host

  mailhog:
    build:
      context: ./config/mailhog
      dockerfile: Dockerfile
    restart: on-failure
    container_name: ${SET_SITE_NAME}_mailhog
    depends_on:
      - php
    ports:
      - target: 8025
        published: ${SET_PORT_MAILHOG}
        protocol: tcp
        mode: host

  redis:
    build:
      context: ./config/redis
      dockerfile: Dockerfile
    restart: on-failure
    container_name: ${SET_SITE_NAME}_redis
    depends_on:
      - php
    expose:
      - 6379

  elastic:
    build:
      context: ./config/elasticsearch
      dockerfile: Dockerfile

    restart: on-failure
    container_name: ${SET_SITE_NAME}_elasticsearch
    expose:
      - 9200
      - 9300
    environment:
      - discovery.type="single-node"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "2048M"
