version: "3.9"
services:
  app:
    # php can be switcable using context path
    build:
      context: ./dockerfiles/php/8.1
      dockerfile: Dockerfile
    container_name: ph
    volumes:
      - ./src:/var/www/htdocs


  server:
    build:
      context: ./dockerfiles/nginx
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    container_name: ng
    volumes:
      - ./src:/var/www/htdocs

# config is copied using the dockerfile
# hotreloading not possible

  db:
    build:
      context: ./dockerfiles/mariadb
      dockerfile: Dockerfile

    restart: on-failure
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: example_database
      MARIADB_USER: example_user
      MARIADB_PASSWORD: example_pass
    volumes:
      - ./dockerfiles/mariadb/storage:/var/lib/mysql
    ports:
      - 8001:3306

# FOR AUTOMATIC LOGIN TO PHPMYADMIN
# - Create custom hyperlink with user and pass as parameters -> in the cli
# or create .env file which will be accessed by both the db service and the phpmyadmin service and the login will be automatic
  phpmyadmin:
    image: phpmyadmin
    links:
      - db
    restart: always
    depends_on:
      - db
    ports:
      - 8002:80
