version: "3.9"
services:
  php:
    build:
      context: ./config/php/${SET_PHP_VERSION}
      dockerfile: Dockerfile
      args:
        SET_XDEBUG_VERSION: ${SET_XDEBUG_VERSION}
        SET_HOST_UID: ${SET_HOST_UID}
        SET_HOST_GID: ${SET_HOST_GID}
    container_name: ${SET_SITE_NAME}_php
    volumes:
      - type: bind
        source: ./src
        target: /var/www/htdocs

  server:
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    ports:
      - 8000:80
      - 8001:443
    container_name: ${SET_SITE_NAME}_nginx
    volumes:
      - ./src:/var/www/htdocs
      - ./config/nginx/certs/server.key:/usr/local/openresty/nginx/certs/server.key
      - ./config/nginx/certs/server.crt:/usr/local/openresty/nginx/certs/server.crt

  db:
    build:
      context: ./config/mariadb
      dockerfile: Dockerfile
      args:
        SET_HOST_UID: ${SET_HOST_UID}

    restart: on-failure
    container_name: ${SET_SITE_NAME}_db
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: example_database
      MARIADB_USER: example_user
      MARIADB_PASSWORD: example_pass

    #user: ${SET_HOST_UID}:${SET_HOST_GID}
    volumes:
      - ./config/mariadb/storage:/var/lib/mysql
    expose:
      - 3306


  phpmyadmin:
    image: phpmyadmin
    restart: on-failure
    container_name: ${SET_SITE_NAME}_phpmyadmin
    depends_on:
      - db
    ports:
      - 8003:80

  mailhog:
    build:
      context: ./config/mailhog
      dockerfile: Dockerfile
    restart: on-failure
    container_name: ${SET_SITE_NAME}_mailhog
    depends_on:
      - php
    ports:
      - 8004:8025

  redis:
    build:
      context: ./config/redis
      dockerfile: Dockerfile
    restart: on-failure
    container_name: ${SET_SITE_NAME}_redis
    depends_on:
      - php
    expose:
      - 6379

  elastic:
    build:
      context: ./config/elasticsearch
      dockerfile: Dockerfile

    restart: on-failure
    container_name: ${SET_SITE_NAME}_elasticsearch
    expose:
      - 9200
      - 9300
    environment:
      - discovery.type="single-node"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "2048M"
